#!/usr/bin/env python3
# This file is placed in the Public Domain.


"build"


## import


import os


## utility


def popen(txt):
    "run command"
    for line in os.popen(txt).readlines():
        print(line.strip())


## runtime


popen("python3 setup.py sdist")
#popen("python3 -m pip install .")